-- [Reconstruída em 2026-10-08]
-- Versão no banco (supabase_migrations.schema_migrations): 20260521070316
-- O SQL abaixo é a cópia EXATA do que foi aplicado via MCP em 21/05/2026,
-- recuperado de schema_migrations.statements. Antes este arquivo só tinha comentários.
-- As referências foram auditadas/corrigidas depois na migração 018_fix_kb_references (versão 20261008011829).
-- ===== SQL original (não editar) =====
-- Migration 011: Seed de referências cientificas curadas
-- Cada uma verificada manualmente (DOI/URL acessivel em 21/05/2026)

INSERT INTO kb_references (citation_key, authors, year, title, publisher_or_journal, doi, url, evidence_type, certainty_level, region, abnt_citation, notes) VALUES

-- ═════ Diretrizes globais (OMS / OIT) ═════
('WHO2022_Guidelines',
 'World Health Organization (WHO)',
 2022,
 'Guidelines on mental health at work',
 'Geneva: World Health Organization',
 NULL,
 'https://www.who.int/publications/i/item/9789240053052',
 'guideline',
 'moderate',
 'global',
 'WORLD HEALTH ORGANIZATION. Guidelines on mental health at work. Geneva: WHO, 2022. ISBN 978-92-4-005305-2. Disponivel em: https://www.who.int/publications/i/item/9789240053052. Acesso em: 21 maio 2026.',
 'Primeira diretriz global da OMS sobre saude mental no trabalho. 5 recomendacoes (intervencoes organizacionais, treinamento de managers, treinamento de workers, intervencoes individuais, retorno ao trabalho). Avaliacao GRADE de certeza da evidencia.'
),

('WHO_ILO2022_PolicyBrief',
 'World Health Organization (WHO); International Labour Organization (ILO)',
 2022,
 'Mental health at work: policy brief',
 'Geneva: WHO/ILO',
 NULL,
 'https://www.who.int/publications/i/item/9789240057944',
 'guideline',
 'moderate',
 'global',
 'WORLD HEALTH ORGANIZATION; INTERNATIONAL LABOUR ORGANIZATION. Mental health at work: policy brief. Geneva: WHO/ILO, 2022. Disponivel em: https://www.who.int/publications/i/item/9789240057944. Acesso em: 21 maio 2026.',
 'Joint WHO/ILO policy brief. Traducao pratica das diretrizes para governos, empregadores, trabalhadores e seus representantes.'
),

('WHO2016_ROI',
 'World Health Organization (WHO)',
 2016,
 'Investing in treatment for depression and anxiety leads to fourfold return',
 'WHO News',
 NULL,
 'https://www.who.int/news/item/13-04-2016-investing-in-treatment-for-depression-and-anxiety-leads-to-fourfold-return',
 'guideline',
 'moderate',
 'global',
 'WORLD HEALTH ORGANIZATION. Investing in treatment for depression and anxiety leads to fourfold return. WHO News, 13 abr. 2016. Disponivel em: https://www.who.int/news/item/13-04-2016-investing-in-treatment-for-depression-and-anxiety-leads-to-fourfold-return. Acesso em: 21 maio 2026.',
 'Estimativa oficial da OMS: cada US$1 investido em tratamento de depressao e ansiedade gera US$4 em retorno (saude + produtividade). Base do calculo de ROI 4:1 amplamente citado.'
),

-- ═════ Dados oficiais brasileiros ═════
('INSS2026',
 'BRASIL. Ministerio da Previdencia Social',
 2026,
 'Previdencia Social concede 546.254 beneficios por incapacidade temporaria por transtornos mentais e comportamentais',
 'Portal Gov.br',
 NULL,
 'https://www.gov.br/previdencia/pt-br/noticias/2026/janeiro/previdencia-social-concede-546-254-beneficios-por-incapacidade-temporaria-por-transtornos-mentais-e-comportamentais',
 'government_data',
 'high',
 'brazil',
 'BRASIL. Ministerio da Previdencia Social. Previdencia Social concede 546.254 beneficios por incapacidade temporaria por transtornos mentais e comportamentais. Brasilia: Portal Gov.br, 28 jan. 2026. Disponivel em: https://www.gov.br/previdencia/pt-br/noticias/2026/janeiro/previdencia-social-concede-546-254-beneficios-por-incapacidade-temporaria-por-transtornos-mentais-e-comportamentais. Acesso em: 21 maio 2026.',
 'Dado oficial INSS 2025: 546.254 beneficios por transtornos mentais (CID Cap V), +15,66% vs 2024. F41 (ansiedade) 166k; mulheres 63,46%. SP=149.375 (maior), MG=83.321, RS=46.738.'
),

('NR1_2024',
 'BRASIL. Ministerio do Trabalho e Emprego',
 2024,
 'Portaria MTE n 1.419, de 27 de agosto de 2024 - Aprova nova redacao do capitulo 1.5 (Gerenciamento de Riscos Ocupacionais) da NR-1',
 'Diario Oficial da Uniao',
 NULL,
 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/sst-portarias/2024/portaria-mte-no-1-419-nr-01-gro-nova-redacao.pdf',
 'guideline',
 'high',
 'brazil',
 'BRASIL. Ministerio do Trabalho e Emprego. Portaria MTE n 1.419, de 27 de agosto de 2024. Aprova a nova redacao do capitulo 1.5 (Gerenciamento de riscos ocupacionais) e altera o Anexo I da Norma Regulamentadora n 1 - Disposicoes Gerais. Diario Oficial da Uniao, Brasilia, 28 ago. 2024. Disponivel em: https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/sst-portarias/2024/portaria-mte-no-1-419-nr-01-gro-nova-redacao.pdf. Acesso em: 21 maio 2026.',
 'Regulacao brasileira que TORNA OBRIGATORIA a inclusao de riscos psicossociais no PGR (Programa de Gerenciamento de Riscos) das empresas. Vigencia a partir de mai. 2025.'
),

('Lei14831_2024',
 'BRASIL. Presidencia da Republica',
 2024,
 'Lei n 14.831, de 27 de marco de 2024 - Institui o Certificado Empresa Promotora da Saude Mental',
 'Diario Oficial da Uniao',
 NULL,
 'https://www2.camara.leg.br/legin/fed/lei/2024/lei-14831-27-marco-2024-795429-publicacaooriginal-171371-pl.html',
 'guideline',
 'high',
 'brazil',
 'BRASIL. Lei n 14.831, de 27 de marco de 2024. Institui o Certificado Empresa Promotora da Saude Mental e estabelece os requisitos para a concessao da certificacao. Diario Oficial da Uniao, Brasilia, 28 mar. 2024. Disponivel em: https://www2.camara.leg.br/legin/fed/lei/2024/lei-14831-27-marco-2024-795429-publicacaooriginal-171371-pl.html. Acesso em: 21 maio 2026.',
 'Marco regulatorio brasileiro do selo Empresa Promotora da Saude Mental. Define requisitos para concessao do certificado pelo Ministerio do Trabalho.'
),

('LGPD',
 'BRASIL. Presidencia da Republica',
 2018,
 'Lei n 13.709, de 14 de agosto de 2018 - Lei Geral de Protecao de Dados Pessoais (LGPD)',
 'Diario Oficial da Uniao',
 NULL,
 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm',
 'guideline',
 'high',
 'brazil',
 'BRASIL. Lei n 13.709, de 14 de agosto de 2018. Lei Geral de Protecao de Dados Pessoais (LGPD). Diario Oficial da Uniao, Brasilia, 15 ago. 2018. Disponivel em: https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm. Acesso em: 21 maio 2026.',
 'Lei brasileira de protecao de dados. Bases legais (Art. 7), direitos do titular (Art. 18), dados sensiveis (Art. 11), segurarca (Art. 46-49). Aplicavel a tratamento de dados de saude mental.'
),

-- ═════ Modelos teoricos validados ═════
('Bakker2023_JDR',
 'BAKKER, A. B.; DEMEROUTI, E.',
 2023,
 'Job Demands-Resources Theory: Ten Years Later',
 'Annual Review of Organizational Psychology and Organizational Behavior',
 '10.1146/annurev-orgpsych-120920-053933',
 'https://www.annualreviews.org/content/journals/10.1146/annurev-orgpsych-120920-053933',
 'theoretical',
 'high',
 'global',
 'BAKKER, A. B.; DEMEROUTI, E. Job Demands-Resources Theory: Ten Years Later. Annual Review of Organizational Psychology and Organizational Behavior, v. 10, p. 25-53, 2023. DOI: 10.1146/annurev-orgpsych-120920-053933. Disponivel em: https://www.annualreviews.org/content/journals/10.1146/annurev-orgpsych-120920-053933. Acesso em: 21 maio 2026.',
 'Atualizacao do modelo JD-R (Job Demands-Resources). Framework teorico que distingue demandas (workload, conflitos) de recursos (autonomia, apoio social) e explica burnout e engajamento. Base teorica de varias intervencoes deste catalogo.'
),

('Ryan2022_SDT',
 'RYAN, R. M.; DUINEVELD, J. J.; DI DOMENICO, S. I. et al.',
 2022,
 'We Know This Much Is (Meta-Analytically) True: A Meta-Review of Meta-Analytic Findings Evaluating Self-Determination Theory',
 'Psychological Bulletin',
 '10.1037/bul0000385',
 'https://selfdeterminationtheory.org/wp-content/uploads/2023/01/2023_RyanDuineveldDiDomenicoEtAl_Meta.pdf',
 'meta_analysis',
 'high',
 'global',
 'RYAN, R. M. et al. We Know This Much Is (Meta-Analytically) True: A Meta-Review of Meta-Analytic Findings Evaluating Self-Determination Theory. Psychological Bulletin, 2022. DOI: 10.1037/bul0000385. Disponivel em: https://selfdeterminationtheory.org/wp-content/uploads/2023/01/2023_RyanDuineveldDiDomenicoEtAl_Meta.pdf. Acesso em: 21 maio 2026.',
 'Meta-revisao de Self-Determination Theory (SDT) de Ryan e Deci. Mostra que satisfacao das 3 necessidades psicologicas basicas (autonomia, competencia, vinculo) tem efeitos robustos em motivacao, performance e bem-estar no trabalho. Cited 460x.'
),

('Edmondson2023_PsychSafety',
 'EDMONDSON, A. C.; BRESMAN, H.',
 2023,
 'Psychological Safety Comes of Age: Observed Themes in an Established Literature',
 'Annual Review of Organizational Psychology and Organizational Behavior',
 '10.1146/annurev-orgpsych-120920-055217',
 'https://www.annualreviews.org/doi/10.1146/annurev-orgpsych-120920-055217',
 'theoretical',
 'high',
 'global',
 'EDMONDSON, A. C.; BRESMAN, H. Psychological Safety Comes of Age: Observed Themes in an Established Literature. Annual Review of Organizational Psychology and Organizational Behavior, v. 10, 2023. DOI: 10.1146/annurev-orgpsych-120920-055217. Disponivel em: https://www.annualreviews.org/doi/10.1146/annurev-orgpsych-120920-055217. Acesso em: 21 maio 2026.',
 'Sintese de 25+ anos de pesquisa sobre seguranca psicologica (Edmondson). Conceito central de cultura de feedback e aprendizagem organizacional.'
),

-- ═════ Instrumentos de pesquisa ═════
('Burr2019_COPSOQ3',
 'BURR, H. et al.',
 2019,
 'The Third Version of the Copenhagen Psychosocial Questionnaire',
 'Safety and Health at Work',
 '10.1016/j.shaw.2019.10.002',
 'https://www.sciencedirect.com/science/article/pii/S2093791118302725',
 'validation_study',
 'high',
 'global',
 'BURR, H. et al. The Third Version of the Copenhagen Psychosocial Questionnaire. Safety and Health at Work, v. 10, n. 4, p. 482-503, 2019. DOI: 10.1016/j.shaw.2019.10.002. Disponivel em: https://www.sciencedirect.com/science/article/pii/S2093791118302725. Acesso em: 21 maio 2026.',
 'Paper de referencia do COPSOQ III (Copenhagen Psychosocial Questionnaire). Validacao multinacional em 28 paises. Cited 717x. Um dos instrumentos usados na plataforma.'
),

('Silva2013_COPSOQ2_PT',
 'SILVA, C. et al.',
 2013,
 'Copenhagen Psychosocial Questionnaire (COPSOQ) - Portugal e paises africanos de lingua oficial portuguesa',
 'ISLA Campus Lisboa',
 NULL,
 'https://www.copsoq-network.org/assets/Uploads/COPSOQ-II-Portuguese.pdf',
 'validation_study',
 'high',
 'europe',
 'SILVA, C. et al. Copenhagen Psychosocial Questionnaire (COPSOQ): Portugal e paises africanos de lingua oficial portuguesa. Lisboa: ISLA-Gaia, 2013. Disponivel em: https://www.copsoq-network.org/assets/Uploads/COPSOQ-II-Portuguese.pdf. Acesso em: 21 maio 2026.',
 'Manual de validacao do COPSOQ II em portugues (N=4.162 trabalhadores). Versoes Short/Medium/Long, dimensoes, percentis de referencia. Base do instrumento principal do Sentinel.'
),

('Demerouti2003_OLBI',
 'DEMEROUTI, E.; BAKKER, A. B.; VARDAKOU, I.; KANTAS, A.',
 2003,
 'The convergent validity of two burnout instruments: A multitrait-multimethod analysis',
 'European Journal of Psychological Assessment',
 '10.1027/1015-5759.19.1.12',
 'https://psycnet.apa.org/record/2003-01998-002',
 'validation_study',
 'high',
 'europe',
 'DEMEROUTI, E. et al. The convergent validity of two burnout instruments: A multitrait-multimethod analysis. European Journal of Psychological Assessment, v. 19, n. 1, p. 12-23, 2003. DOI: 10.1027/1015-5759.19.1.12.',
 'Validacao original do OLBI (Oldenburg Burnout Inventory). 2 subescalas (exaustao, desengajamento), 16 itens. Usado como instrumento alternativo ao MBI.'
),

('Spector1985_JSS',
 'SPECTOR, P. E.',
 1985,
 'Measurement of human service staff satisfaction: development of the Job Satisfaction Survey',
 'American Journal of Community Psychology',
 '10.1007/BF00929796',
 'https://pubmed.ncbi.nlm.nih.gov/4083275/',
 'validation_study',
 'high',
 'usa',
 'SPECTOR, P. E. Measurement of human service staff satisfaction: development of the Job Satisfaction Survey. American Journal of Community Psychology, v. 13, n. 6, p. 693-713, 1985. DOI: 10.1007/BF00929796. Disponivel em: https://pubmed.ncbi.nlm.nih.gov/4083275/. Acesso em: 21 maio 2026.',
 'Instrumento original JSS (Job Satisfaction Survey), 36 itens, 9 subescalas. Usado como instrumento alternativo no Sentinel para medir satisfacao no trabalho.'
),

-- ═════ Meta-analises de intervencoes ═════
('Cochrane2024_OrgHealthcare',
 'KIDA, R. et al.',
 2024,
 'The effects of different types of organisational workplace mental health interventions in healthcare workers',
 'International Archives of Occupational and Environmental Health',
 '10.1007/s00420-024-02065-z',
 'https://link.springer.com/article/10.1007/s00420-024-02065-z',
 'systematic_review',
 'moderate',
 'global',
 'KIDA, R. et al. The effects of different types of organisational workplace mental health interventions in healthcare workers: a systematic review. International Archives of Occupational and Environmental Health, 2024. DOI: 10.1007/s00420-024-02065-z. Disponivel em: https://link.springer.com/article/10.1007/s00420-024-02065-z. Acesso em: 21 maio 2026.',
 'Revisao sistematica de 22 estudos (2024). 68% das intervencoes organizacionais melhoraram saude mental; mais consistente em burnout (11/13 estudos). STRONG evidence para Job and Task Modifications; MODERATE para Flexible work, Physical environment.'
),

('PLOS2022_OrgInterventions',
 'GRAY, P. et al.',
 2022,
 'The effectiveness of organisational-level workplace mental health interventions on mental health and wellbeing',
 'PLOS ONE',
 '10.1371/journal.pone.0277114',
 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0277114',
 'systematic_review',
 'moderate',
 'global',
 'GRAY, P. et al. The effectiveness of organisational-level workplace mental health interventions on mental health and wellbeing: a systematic review. PLOS ONE, v. 17, n. 11, e0277114, 2022. DOI: 10.1371/journal.pone.0277114. Disponivel em: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0277114. Acesso em: 21 maio 2026.',
 'Revisao sistematica de intervencoes ORGANIZACIONAIS (nao individuais) em saude mental no trabalho. Inclui modificacoes em demandas, recursos, lideranca, cultura.'
),

('JMIR2025_Digital',
 'OBRIEN, J. et al.',
 2025,
 'Effectiveness of Digital Mental Health Interventions in the Workplace',
 'JMIR Mental Health',
 '10.2196/67785',
 'https://mental.jmir.org/2025/1/e67785',
 'systematic_review',
 'moderate',
 'global',
 'O''BRIEN, J. et al. Effectiveness of Digital Mental Health Interventions in the Workplace: Systematic Review and Meta-analysis. JMIR Mental Health, 2025. DOI: 10.2196/67785. Disponivel em: https://mental.jmir.org/2025/1/e67785. Acesso em: 21 maio 2026.',
 'Meta-analise 2025 sobre intervencoes digitais (TCC online, mindfulness app, stress management). Efeitos pequenos a moderados em sintomas depressivos e ansiosos.'
),

('Wiley2022_FlexibleWork',
 'WHEATLEY, D.',
 2022,
 'A Meta-Analysis of Antecedents and Outcomes of Flexible Working Arrangements',
 'Journal of Organizational Behavior',
 '10.1002/job.2896',
 'https://onlinelibrary.wiley.com/doi/full/10.1002/job.2896',
 'meta_analysis',
 'moderate',
 'global',
 'WHEATLEY, D. A Meta-Analysis of Antecedents and Outcomes of Flexible Working Arrangements. Journal of Organizational Behavior, 2022. DOI: 10.1002/job.2896. Disponivel em: https://onlinelibrary.wiley.com/doi/full/10.1002/job.2896. Acesso em: 21 maio 2026.',
 'Meta-analise: arranjos flexiveis de trabalho (FWA) associados a maior satisfacao, comprometimento organizacional, autonomia e satisfacao com a vida. Reducao de absenteismo.'
),

('Gallup_Q12_2020',
 'HARTER, J. K. et al.',
 2020,
 'The Relationship Between Engagement at Work and Organizational Outcomes - 2020 Q12 Meta-Analysis (11th Edition)',
 'Gallup Press',
 NULL,
 'https://www.gallup.com/workplace/321725/gallup-q12-meta-analysis-report.aspx',
 'meta_analysis',
 'moderate',
 'global',
 'HARTER, J. K. et al. The Relationship Between Engagement at Work and Organizational Outcomes: 2020 Q12 Meta-Analysis - 11th Edition. Washington: Gallup, 2020. Disponivel em: https://www.gallup.com/workplace/321725/gallup-q12-meta-analysis-report.aspx. Acesso em: 21 maio 2026.',
 'Meta-analise Gallup Q12 (11a edicao, 2020). 112.312 unidades de negocio em 96 paises. Top quartil de engajamento: 81% menos absenteismo, 18% menos turnover (alta retencao), 23% mais lucratividade.'
),

('TransfLeadership2023',
 'INCEOGLU, I. et al.',
 2022,
 'Leader behaviours and employee well-being: A meta-analytic review',
 'Frontiers in Psychology',
 '10.3389/fpsyg.2022.852685',
 'https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2022.852685/full',
 'meta_analysis',
 'high',
 'global',
 'INCEOGLU, I. et al. Leader behaviours and employee well-being: A meta-analytic review. Frontiers in Psychology, v. 13, 2022. DOI: 10.3389/fpsyg.2022.852685. Disponivel em: https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2022.852685/full. Acesso em: 21 maio 2026.',
 'Meta-analise sobre o impacto de estilos de lideranca no bem-estar. Lideranca transformacional, LMX e lideranca orientada a relacionamento associadas a menor burnout e mais satisfacao.'
),

('Maslach2016_Burnout',
 'MASLACH, C.; LEITER, M. P.',
 2016,
 'Understanding the burnout experience: recent research and its implications for psychiatry',
 'World Psychiatry',
 '10.1002/wps.20311',
 'https://onlinelibrary.wiley.com/doi/10.1002/wps.20311',
 'theoretical',
 'high',
 'global',
 'MASLACH, C.; LEITER, M. P. Understanding the burnout experience: recent research and its implications for psychiatry. World Psychiatry, v. 15, n. 2, p. 103-111, 2016. DOI: 10.1002/wps.20311.',
 'Atualizacao do modelo MBI de burnout (Maslach Burnout Inventory) com novas perspectivas: 6 areas de desajuste (carga, controle, recompensa, comunidade, justica, valores).'
),

('Frontiers2020_Bullying',
 'GILLEN, P. A. et al.',
 2020,
 'Outcomes of a Proximal Workplace Intervention Against Workplace Bullying',
 'Frontiers in Psychology',
 '10.3389/fpsyg.2020.02013',
 'https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2020.02013/full',
 'rct',
 'moderate',
 'global',
 'GILLEN, P. A. et al. Outcomes of a Proximal Workplace Intervention Against Workplace Bullying and Harassment. Frontiers in Psychology, 2020. DOI: 10.3389/fpsyg.2020.02013. Disponivel em: https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2020.02013/full. Acesso em: 21 maio 2026.',
 'Ensaio randomizado de intervencao anti-bullying em workplace. Avalia outcomes de programas estruturados de prevencao e remediacao.'
);
