-- Acentos nos textos do COPSOQ III e do OLBI (perguntas, escalas e instrumentos).
-- Só a grafia muda: nenhum sentido, ordem ou pontuação de pergunta é alterado.

-- copsoq_iii: perguntas
UPDATE public.questionnaire_items SET text = 'A sua carga de trabalho se acumula por não poder ser realizada no dia a dia?' WHERE text = 'A sua carga de trabalho se acumula por nao poder ser realizada no dia a dia?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você não tem tempo para completar todas as tarefas do seu trabalho?' WHERE text = 'Com que frequencia voce nao tem tempo para completar todas as tarefas do seu trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você fica atrasado(a) com o seu trabalho?' WHERE text = 'Voce fica atrasado(a) com o seu trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você precisa trabalhar muito rápido?' WHERE text = 'Voce precisa trabalhar muito rapido?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'O seu trabalho exige que você se lembre de muitas coisas?' WHERE text = 'O seu trabalho exige que voce se lembre de muitas coisas?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'O seu trabalho exige que você tome decisões difíceis?' WHERE text = 'O seu trabalho exige que voce tome decisoes dificeis?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'O seu trabalho exige que você proponha novas ideias?' WHERE text = 'O seu trabalho exige que voce proponha novas ideias?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'O seu trabalho é emocionalmente desgastante?' WHERE text = 'O seu trabalho e emocionalmente desgastante?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'O seu trabalho exige que você se envolva emocionalmente?' WHERE text = 'O seu trabalho exige que voce se envolva emocionalmente?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'O seu trabalho exige que você esconda seus sentimentos?' WHERE text = 'O seu trabalho exige que voce esconda seus sentimentos?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você tem influência sobre a quantidade de trabalho que lhe é atribuída?' WHERE text = 'Voce tem influencia sobre a quantidade de trabalho que lhe e atribuida?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você pode influenciar as decisões sobre o seu trabalho?' WHERE text = 'Voce pode influenciar as decisoes sobre o seu trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você tem voz ativa sobre o que e como faz no seu trabalho?' WHERE text = 'Voce tem voz ativa sobre o que e como faz no seu trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'O seu trabalho lhe dá oportunidades de desenvolver suas competências?' WHERE text = 'O seu trabalho lhe da oportunidades de desenvolver suas competencias?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você pode usar suas habilidades ou conhecimentos no seu trabalho?' WHERE text = 'Voce pode usar suas habilidades ou conhecimentos no seu trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'O seu trabalho tem significado para você?' WHERE text = 'O seu trabalho tem significado para voce?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você sente que o trabalho que faz é importante?' WHERE text = 'Voce sente que o trabalho que faz e importante?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você se sente motivado(a) e envolvido(a) com o seu trabalho?' WHERE text = 'Voce se sente motivado(a) e envolvido(a) com o seu trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você gosta de contar às pessoas sobre o seu local de trabalho?' WHERE text = 'Voce gosta de contar as pessoas sobre o seu local de trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você sente que os problemas do seu local de trabalho são também seus?' WHERE text = 'Voce sente que os problemas do seu local de trabalho sao tambem seus?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você sente que o seu local de trabalho tem grande significado pessoal para você?' WHERE text = 'Voce sente que o seu local de trabalho tem grande significado pessoal para voce?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'No seu local de trabalho, você é informado(a) com antecedência sobre decisões importantes?' WHERE text = 'No seu local de trabalho, voce e informado(a) com antecedencia sobre decisoes importantes?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você recebe toda a informação necessária para fazer bem o seu trabalho?' WHERE text = 'Voce recebe toda a informacao necessaria para fazer bem o seu trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você sabe exatamente o que se espera de você no trabalho?' WHERE text = 'Voce sabe exatamente o que se espera de voce no trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você sabe exatamente quais são suas responsabilidades?' WHERE text = 'Voce sabe exatamente quais sao suas responsabilidades?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você precisa fazer coisas que acha desnecessárias no trabalho?' WHERE text = 'Voce precisa fazer coisas que acha desnecessarias no trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Recebe exigências contraditórias no trabalho?' WHERE text = 'Recebe exigencias contraditorias no trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você precisa fazer coisas que vão contra os seus valores?' WHERE text = 'Voce precisa fazer coisas que vao contra os seus valores?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Até que ponto seu superior imediato se certifica de que cada membro da equipe tem boas oportunidades de desenvolvimento?' WHERE text = 'Ate que ponto seu superior imediato se certifica de que cada membro da equipe tem boas oportunidades de desenvolvimento?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Até que ponto seu superior imediato dá prioridade à satisfação no trabalho?' WHERE text = 'Ate que ponto seu superior imediato da prioridade a satisfacao no trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Até que ponto seu superior imediato é bom em planejar o trabalho?' WHERE text = 'Ate que ponto seu superior imediato e bom em planejar o trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Até que ponto seu superior imediato é bom em resolver conflitos?' WHERE text = 'Ate que ponto seu superior imediato e bom em resolver conflitos?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência seu superior imediato está disposto a ouvi-lo(a) sobre seus problemas no trabalho?' WHERE text = 'Com que frequencia seu superior imediato esta disposto a ouvi-lo(a) sobre seus problemas no trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você recebe ajuda e apoio do seu superior imediato?' WHERE text = 'Com que frequencia voce recebe ajuda e apoio do seu superior imediato?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência seus colegas estão dispostos a ouvi-lo(a) sobre seus problemas no trabalho?' WHERE text = 'Com que frequencia seus colegas estao dispostos a ouvi-lo(a) sobre seus problemas no trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você recebe ajuda e apoio dos seus colegas?' WHERE text = 'Com que frequencia voce recebe ajuda e apoio dos seus colegas?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Existe um bom espírito de equipe entre você e seus colegas?' WHERE text = 'Existe um bom espirito de equipe entre voce e seus colegas?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Existe boa colaboração entre os colegas no trabalho?' WHERE text = 'Existe boa colaboracao entre os colegas no trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você se sente parte de uma comunidade no seu local de trabalho?' WHERE text = 'Voce se sente parte de uma comunidade no seu local de trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'O seu trabalho é reconhecido e apreciado pela chefia?' WHERE text = 'O seu trabalho e reconhecido e apreciado pela chefia?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você é tratado(a) de forma justa no seu local de trabalho?' WHERE text = 'Voce e tratado(a) de forma justa no seu local de trabalho?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Os conflitos são resolvidos de forma justa?' WHERE text = 'Os conflitos sao resolvidos de forma justa?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'As sugestões dos funcionários são tratadas com seriedade pela chefia?' WHERE text = 'As sugestoes dos funcionarios sao tratadas com seriedade pela chefia?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'A chefia esconde informações dos funcionários?' WHERE text = 'A chefia esconde informacoes dos funcionarios?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Os funcionários podem expressar suas opiniões e sentimentos?' WHERE text = 'Os funcionarios podem expressar suas opinioes e sentimentos?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você se preocupa em ficar desempregado(a)?' WHERE text = 'Voce se preocupa em ficar desempregado(a)?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você se preocupa com ser transferido(a) para outro trabalho contra sua vontade?' WHERE text = 'Voce se preocupa com ser transferido(a) para outro trabalho contra sua vontade?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você se preocupa com novas tecnologias tornarem você dispensável?' WHERE text = 'Voce se preocupa com novas tecnologias tornarem voce dispensavel?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Em relação às suas condições de trabalho, quão satisfeito(a) está?' WHERE text = 'Em relacao as suas condicoes de trabalho, quao satisfeito(a) esta?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Em relação às suas perspectivas de trabalho, quão satisfeito(a) está?' WHERE text = 'Em relacao as suas perspectivas de trabalho, quao satisfeito(a) esta?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Em relação à forma como suas habilidades são utilizadas, quão satisfeito(a) está?' WHERE text = 'Em relacao a forma como suas habilidades sao utilizadas, quao satisfeito(a) esta?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Em relação ao seu trabalho de modo geral, quão satisfeito(a) está?' WHERE text = 'Em relacao ao seu trabalho de modo geral, quao satisfeito(a) esta?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você sente que o trabalho ocupa tanto do seu tempo que isso tem um efeito negativo na sua vida privada?' WHERE text = 'Voce sente que o trabalho ocupa tanto do seu tempo que isso tem um efeito negativo na sua vida privada?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você se sente esgotado(a)?' WHERE text = 'Com que frequencia voce se sente esgotado(a)?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você se sente fisicamente exausto(a)?' WHERE text = 'Com que frequencia voce se sente fisicamente exausto(a)?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você se sente emocionalmente exausto(a)?' WHERE text = 'Com que frequencia voce se sente emocionalmente exausto(a)?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você se sente cansado(a)?' WHERE text = 'Com que frequencia voce se sente cansado(a)?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você tem dificuldade em relaxar?' WHERE text = 'Com que frequencia voce tem dificuldade em relaxar?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você fica irritado(a)?' WHERE text = 'Com que frequencia voce fica irritado(a)?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você se sente tenso(a)?' WHERE text = 'Com que frequencia voce se sente tenso(a)?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Com que frequência você se sente estressado(a)?' WHERE text = 'Com que frequencia voce se sente estressado(a)?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Em geral, como você avalia a sua saúde?' WHERE text = 'Em geral, como voce avalia a sua saude?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você foi exposto(a) a bullying no local de trabalho nos últimos 12 meses?' WHERE text = 'Voce foi exposto(a) a bullying no local de trabalho nos ultimos 12 meses?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você foi exposto(a) a assédio sexual no trabalho nos últimos 12 meses?' WHERE text = 'Voce foi exposto(a) a assedio sexual no trabalho nos ultimos 12 meses?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você foi exposto(a) a ameaças de violência no trabalho nos últimos 12 meses?' WHERE text = 'Voce foi exposto(a) a ameacas de violencia no trabalho nos ultimos 12 meses?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_items SET text = 'Você foi exposto(a) a violência física no trabalho nos últimos 12 meses?' WHERE text = 'Voce foi exposto(a) a violencia fisica no trabalho nos ultimos 12 meses?' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');

-- olbi: perguntas
UPDATE public.questionnaire_items SET text = 'Há dias em que me sinto cansado(a) antes mesmo de chegar ao trabalho.' WHERE text = 'Ha dias em que me sinto cansado(a) antes mesmo de chegar ao trabalho.' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'olbi');
UPDATE public.questionnaire_items SET text = 'Ultimamente, tendo a pensar menos durante o trabalho e fazê-lo quase mecanicamente.' WHERE text = 'Ultimamente, tendo a pensar menos durante o trabalho e faze-lo quase mecanicamente.' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'olbi');
UPDATE public.questionnaire_items SET text = 'Às vezes me sinto enjoado(a) com as tarefas do meu trabalho.' WHERE text = 'As vezes me sinto enjoado(a) com as tarefas do meu trabalho.' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'olbi');
UPDATE public.questionnaire_items SET text = 'Este é o único tipo de trabalho que me imagino fazendo.' WHERE text = 'Este e o unico tipo de trabalho que me imagino fazendo.' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'olbi');
UPDATE public.questionnaire_items SET text = 'Sinto que o meu trabalho é cada vez mais uma experiência positiva.' WHERE text = 'Sinto que o meu trabalho e cada vez mais uma experiencia positiva.' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'olbi');

-- copsoq_iii: escalas
UPDATE public.questionnaire_scales SET name = 'Demandas para Esconder Emoções' WHERE name = 'Demandas para Esconder Emocoes' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_scales SET name = 'Influência no Trabalho' WHERE name = 'Influencia no Trabalho' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_scales SET name = 'Conflito de Papéis' WHERE name = 'Conflito de Papeis' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_scales SET name = 'Qualidade da Liderança' WHERE name = 'Qualidade da Lideranca' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_scales SET name = 'Justiça e Respeito' WHERE name = 'Justica e Respeito' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_scales SET name = 'Confiança em Relação à Chefia' WHERE name = 'Confianca em Relacao a Chefia' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_scales SET name = 'Insegurança no Trabalho' WHERE name = 'Inseguranca no Trabalho' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_scales SET name = 'Satisfação no Trabalho' WHERE name = 'Satisfacao no Trabalho' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_scales SET name = 'Conflito Trabalho-Família' WHERE name = 'Conflito Trabalho-Familia' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');
UPDATE public.questionnaire_scales SET name = 'Saúde Geral' WHERE name = 'Saude Geral' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'copsoq_iii');

-- olbi: escalas
UPDATE public.questionnaire_scales SET name = 'Exaustão' WHERE name = 'Exaustao' AND instrument_id = (SELECT id FROM public.questionnaire_instruments WHERE code = 'olbi');

-- instrumentos
UPDATE public.questionnaire_instruments SET description = 'Inventário de Burnout de Oldenburg (Demerouti et al., 2003). Avalia duas dimensões centrais do burnout: exaustão e desengajamento. 16 itens com escala Likert de 4 pontos (concordância).' WHERE code = 'olbi' AND description = 'Inventario de Burnout de Oldenburg (Demerouti et al., 2003). Avalia duas dimensoes centrais do burnout: exaustao e desengajamento. 16 itens com escala Likert de 4 pontos (concordancia).';
UPDATE public.questionnaire_instruments SET name = 'COPSOQ III — Versão Média' WHERE code = 'copsoq_iii' AND name = 'COPSOQ III — Versao Media';
UPDATE public.questionnaire_instruments SET description = 'Copenhagen Psychosocial Questionnaire, 3ª edição (Burr et al., 2019). Versão Média com 70 itens em 26 escalas. Avalia fatores psicossociais no trabalho com escores de 0-100. Escala Work Engagement (UWES) excluída por exigir licença comercial.' WHERE code = 'copsoq_iii' AND description = 'Copenhagen Psychosocial Questionnaire, 3a edicao (Burr et al., 2019). Versao Media com 70 itens em 26 escalas. Avalia fatores psicossociais no trabalho com escores de 0-100. Escala Work Engagement (UWES) excluida por exigir licenca comercial.';
